### ISSUE TITLE
a little problem

### ISSUE THREAD

**Issue by HHhyJJ** [tensorly/viz#18]
When I used the function tlviz.visualisation.core_element_plot to show some results, I found that np.bool is used on line 651 of visualisation.py, which has been deprecated since NumPy 1.20.0, and that made an error in my program. It's successfully run after I changed np.bool to np.bool_ or bool. There may be other similar errors and I hope it can be fixed.

**Comment by yngvem** [comment]
Thank you for letting us know @HHhyJJ! I think I fixed it in the `issue_18` branch, but I'm having some issue with one of the doctests failing due to a numpy upgrade. Once I've found a solution to these tests, I'll merge the fix into main.

**Comment by yngvem** [comment]
Should be fixed now, thanks again @HHhyJJ!

**Comment by HHhyJJ** [comment]
Thank you very much, the tensorly-viz help me a lot and thanks your work!
