### ISSUE TITLE
Amino Acids Dataset Download URL Doesn't Lead to a File

### ISSUE THREAD

**Issue by jonathanstathakis** [tensorly/viz#22]
I am trying to recreate the PARAFAC demonstration in the [JOSS publication](https://www.theoj.org/joss-papers/joss.04754/10.21105.joss.04754.pdf) (and the labelled decompositions [tutorial](https://tensorly.org/viz/stable/auto_examples/plot_labelled_decompositions.html#sphx-glr-download-auto-examples-plot-labelled-decompositions-py)), however I am running into an error when I try to load the amino acid toy dataset. 

```
---------------------------------------------------------------------------
BadZipFile                                Traceback (most recent call last)
/Users/.../tlviz_parafac_tutorial.ipynb Cell 1 line 2
     17 path = "/Users/jonathan/Downloads/claus.mat"
     18 io.loadmat(path)
---> 20 data = tlviz.data.load_aminoacids(save_data=True)
     21 cp_tensor = fit_parafac(data, 3, num_inits=3)
     22 tlviz.visualisation.components_plot(cp_tensor)

File ~/Library/Caches/pypoetry/virtualenvs/pca-analysis-6KQS4gUX-py3.12/lib/python3.12/site-packages/tlviz/data.py:73, in load_aminoacids(save_data)
     70 if filename.is_file():
     71     return xr.open_dataarray(filename)
---> 73 aminoacids_zip = RemoteZip("http://models.life.ku.dk/sites/default/files/Amino_Acid_fluo.zip")
     74 matlab_variables = loadmat(aminoacids_zip.extract_file("amino.mat"))
     76 I, K, J = matlab_variables["DimX"].squeeze().astype(int)

File ~/Library/Caches/pypoetry/virtualenvs/pca-analysis-6KQS4gUX-py3.12/lib/python3.12/site-packages/tlviz/data.py:26, in RemoteZip.__init__(self, url)
     24 def __init__(self, url):
     25     req = requests.get(url)
---> 26     self.zip = zipfile.ZipFile(BytesIO(req.content))

File ~/.pyenv/versions/3.12.2/lib/python3.12/zipfile/__init__.py:1341, in ZipFile.__init__(self, file, mode, compression, allowZip64, compresslevel, strict_timestamps, metadata_encoding)
   1339 try:
   1340     if mode == 'r':
-> 1341         self._RealGetContents()
   1342     elif mode in ('w', 'x'):
   1343         # set the modified flag so central directory gets written
   1344         # even if no files are added to the archive
   1345         self._didModify = True

File ~/.pyenv/versions/3.12.2/lib/python3.12/zipfile/__init__.py:1408, in ZipFile._RealGetContents(self)
   1406     raise BadZipFile("File is not a zip file")
   1407 if not endrec:
-> 1408     raise BadZipFile("File is not a zip file")
   1409 if self.debug > 1:
   1410     print(endrec)

BadZipFile: File is not a zip file
```

On investigation it appears that the hardcoded URL: "http://models.life.ku.dk/sites/default/files/Amino_Acid_fluo.zip" does not lead to the expected zip file, instead redirecting to "https://ucphchemometrics.com/" homepage.

I have located an alternative source for the dataset on that website at "https://ucphchemometrics.com/wp-content/uploads/2023/05/claus.zip", however it appears that the dataset structure is different. For example, the code in `tlviz.data.load_aminoacids` expects the dataset dict (once parsed) to contain a "DimX" key, whereas the dataset contains the following keys: `dict_keys(['__header__', '__version__', '__globals__', 'evalme', 'X', 'y', 'readme', 'ExAx', 'EmAx'])`.

I have almost no background in working with fluorescence data, or MATLAB, however I can perceive that DimX should be a tuple of integers describing the length of each mode, given the following lines:

```
I, K, J = matlab_variables["DimX"].squeeze().astype(int)
X = matlab_variables["X"].reshape(I, J, K)
```

but I cant find anything matching that structure within the dataset.

I was hoping to to use this code as a practical demonstration of working with tensor data, so I don't have the know-how to adapt the dataset I found with the `load_aminoacids` code. Perhaps the easiest fix would be if the maintainers were able to provide a working URL to the `amino.mat` data file?

**Comment by yngvem** [comment]
Just answering on my phone now to try and get some more information before digging into it.

That's odd, thanks a lot for filing the issue! I believe we should have fixed that in the latest version of tlviz. Which version are you running (You can check that by running `import tlviz; print(tlviz.__version__)`)? And importantly, how did you install it (I'm guessing with poetry, based on your traceback)?

**Comment by jonathanstathakis** [comment]
> Just answering on my phone now to try and get some more information before digging into it.
> 
> That's odd, thanks a lot for filing the issue! I believe we should have fixed that in the latest version of tlviz. Which version are you running (You can check that by running `import tlviz; print(tlviz.__version__)`)? And importantly, how did you install it (I'm guessing with poetry, based on your traceback)?

Ah, I didn't think to check the version! You are correct, I installed it via poetry `poetry add tlviz`, which in hindsight was a tad careless, and it installed version 0.1.1. Reinstalling with `poetry add tensorly-viz` correctly installed version 0.1.7, which is able to load the dataset correctly. Evidently, the first command installed [this package](https://pypi.org/project/TLViz/).

Thanks for your help and prompt followup. I'll close this issue now.
