### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorly'

### ISSUE THREAD

**Issue by yiitozer** [tensorly/viz#5]
tensorly library doesn't seem to be a prerequisite of the pip package. I saw that this is available in the [docs] [test] sections. Maybe you can explicitly mention this in the readme.

**Comment by MarieRoald** [comment]
Hi @yiitozer, thank you for pointing this out! I updated the [installation guide](https://tensorly.org/viz/stable/installation.html) to give more detailed instructions for installing the different dependencies for the documentation and tests and updated the README to point to the installation guide. Do you think this helps to make it sufficiently clear? (Thanks to this issue, I also found a small bug in the _tl_utils module, which is now fixed).

**Comment by yiitozer** [comment]
alright, thanks!
