### ISSUE TITLE
workflow runs failed

### ISSUE THREAD

**Issue by yiitozer** [tensorly/viz#7]
I could run all the tests successfully on my local machine following the instructions, but I have just seen that your last workflow run has failed. Is there a specific reason for this?

https://github.com/openjournals/joss-reviews/issues/4754

**Comment by yngvem** [comment]
I couldn't find any workflow that failed with recent versions of the main branch, so I'm guessing that the failing workflow that you are referring to is for an unmerged pull request maybe?

**Comment by yiitozer** [comment]
Ah OK, I have overseen that. Thank you. I'm closing this issue.
